AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/LineLength:
  Max: 100
  AllowURI: true
  IgnoredPatterns: ['\A#', '\A\t+#', '\A\s+#']

Metrics/PerceivedComplexity:
  Description: A complexity metric geared towards measuring complexity for a human reader.
  Enabled: false
  Max: 7
